# -*- coding: utf-8 -*-
"""OOP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jhMzykkTdeXQufWQ95qH35ciJBqS4TIo
"""

class Person:
  pass
p = Person()
print(p)

#Attributes of a class
# Methods
class Person:
  def say_hi(self):
    print('Hello, how are you?')
p = Person()
p.say_hi()

#Data Fields
class Person:

  def __init__(self,age):
    self.age = age

  def say_hi(self):
    print('Hi I am {:d} years old' .format(self.age))

p = Person(20)
p.say_hi()

#Class Variable vs Object Variable
def is_even(num):
  """
  Input : an integer
  Output: if input is even (True for even, False for not)
  """
  return num %2 == 0
  help(is_even)

  pi_value = 3.14
  print ("The value of PI is {:d}".format(pi_value))